package br.com.gestaodeestoque.Views;

import br.com.gestaodeestoque.Models.ClientesModelo;
import br.com.gestaodeestoque.Models.FuncionarioModelo;
import br.com.gestaodeestoque.Models.ItensPedidosModelo;
import br.com.gestaodeestoque.Models.PedidosModelo;
import br.com.gestaodeestoque.Models.ProdutoModelo;
import br.com.gestaodeestoque.dao.ClientesDAO;
import br.com.gestaodeestoque.dao.ItensPedidosDAO;
import br.com.gestaodeestoque.dao.PedidosDAO;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

public class FinalizarPedido extends javax.swing.JDialog {

    static List<ItensPedidosModelo> listaitenspedidosmodelo;
    static FuncionarioModelo funcionariomodelo;
    static double total;
    PedidosModelo pedidosmodelo;

    public FinalizarPedido(java.awt.Frame parent, boolean modal, List<ItensPedidosModelo> listaitenspedidosmodelo, FuncionarioModelo funcionarioatual, double total) {
        super(parent, modal);
        initComponents();
        this.listaitenspedidosmodelo = listaitenspedidosmodelo;
        funcionariomodelo = funcionarioatual;
        this.total = total;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        txtHoraRetirada = new javax.swing.JTextField();
        jToolBar1 = new javax.swing.JToolBar();
        btnGerenciarClientes = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();
        cmbClientes = new javax.swing.JComboBox();
        jLabel3 = new javax.swing.JLabel();
        txtDesconto = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        btnVoltar = new javax.swing.JButton();
        btnFinalizar = new javax.swing.JButton();
        lblImagemFundo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setText("Horário de Retirada");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 111, -1, -1));
        getContentPane().add(txtHoraRetirada, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 131, 236, -1));

        jToolBar1.setFloatable(false);
        jToolBar1.setRollover(true);

        btnGerenciarClientes.setIcon(new javax.swing.ImageIcon(getClass().getResource("/icons/Add User Male_39px.png"))); // NOI18N
        btnGerenciarClientes.setText("Gerenciar Clientes");
        btnGerenciarClientes.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGerenciarClientesActionPerformed(evt);
            }
        });
        jToolBar1.add(btnGerenciarClientes);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 458, 44));

        jLabel2.setText("Cliente");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 162, -1, -1));

        getContentPane().add(cmbClientes, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 182, 236, -1));

        jLabel3.setText("Data");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 62, -1, -1));
        getContentPane().add(txtDesconto, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 233, 94, -1));

        jLabel4.setText("Desconto");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(204, 213, -1, -1));

        jLabel5.setText("Total");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 213, -1, -1));

        txtTotal.setEnabled(false);
        getContentPane().add(txtTotal, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 233, 94, -1));

        btnVoltar.setText("Voltar");
        getContentPane().add(btnVoltar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 291, -1, -1));

        btnFinalizar.setText("Finalizar");
        btnFinalizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnFinalizarActionPerformed(evt);
            }
        });
        getContentPane().add(btnFinalizar, new org.netbeans.lib.awtextra.AbsoluteConstraints(377, 291, -1, -1));

        lblImagemFundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesteste/fundo_opaco.png"))); // NOI18N
        getContentPane().add(lblImagemFundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 40, 530, 360));

        setSize(new java.awt.Dimension(482, 373));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    public void listarClientes() {
        ClientesDAO clientesdao = new ClientesDAO();
        List<ClientesModelo> listadeclientes = clientesdao.listarClientes();
        cmbClientes.removeAllItems();
        cmbClientes.addItem("");
        for (ClientesModelo clientesmodelo : listadeclientes) {
            cmbClientes.addItem(clientesmodelo);
        }
    }

    public PedidosModelo cadastrarPedido() {
        try {
            PedidosModelo pedidosmodelo = new PedidosModelo();
            ClientesModelo clientemodelo = new ClientesModelo();

            clientemodelo = (ClientesModelo) cmbClientes.getSelectedItem();
            pedidosmodelo.setCliente(clientemodelo);
            pedidosmodelo.setFuncionariomodelo(funcionariomodelo);
            SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");
//            String dataformatada = formatador.format(txtData.getDate());
//            pedidosmodelo.setData(dataformatada);
            pedidosmodelo.setHorario_retirada(txtHoraRetirada.getText());
            pedidosmodelo.setTotal(this.total);
            if(!txtDesconto.getText().equals(""))
            {
            pedidosmodelo.setDesconto(Double.parseDouble(txtDesconto.getText()));
            }else{pedidosmodelo.setDesconto(0);}
            PedidosDAO pedidosdao = new PedidosDAO();
//            this.pedidosmodelo = pedidosmodelo;
            this.pedidosmodelo = pedidosdao.cadastrarPedido(pedidosmodelo);
            
            JOptionPane.showMessageDialog(null, "Pedido cadastrado com sucesso.");
            return this.pedidosmodelo; 
        } catch (Exception e) {
            throw new RuntimeException(e);
        }
    }

    public void cadastrarItensPedidos() {
        try {
            //            ItensPedidosModelo itensmodelo = this.listaitenspedidosmodelo;
//            PedidosModelo pedido = new PedidosDAO().idPedidoEmAberta();
            //CADASTRAR OS ITENS DA TABELA
            for (ItensPedidosModelo itensmodelo : listaitenspedidosmodelo) {

                itensmodelo.setPedido(this.pedidosmodelo);
//                ProdutoModelo produto = new ProdutoModelo();
//                produto.setIdProduto(Integer.parseInt(itensmodelo.getProduto()));
//                itensmodelo.setProduto(produto);
//                itensmodelo.setQtd(Integer.parseInt(tabela_itens_venda.getValueAt(l, 4).toString()));
//                itensmodelo.setValorUni(Double.parseDouble(tabela_itens_venda.getValueAt(l, 5).toString()));
//                itensmodelo.setDesconto(Double.parseDouble(tabela_itens_venda.getValueAt(l, 6).toString()));
//                itensmodelo.setSubtotal(Double.parseDouble(tabela_itens_venda.getValueAt(l, 7).toString()));

                ItensPedidosDAO itempedidodao = new ItensPedidosDAO();
                itempedidodao.cadastraItensPedidos(itensmodelo);
            }
//            JOptionPane.showMessageDialog(null, "Item Pedido cadastrado com sucesso.");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Erro ao cadastrar item pedido: " + e);
        }

    }
    private void btnFinalizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnFinalizarActionPerformed
        // ESSE FINALIZAR VAI SER O BIXO.
        try {
            this.pedidosmodelo =  cadastrarPedido();
            cadastrarItensPedidos();
            this.dispose();
            if(JOptionPane.showConfirmDialog(null, "Deseja inserir o pagamento agora ?", "Concluir", 0)== JOptionPane.YES_OPTION)
            {
                FrmDialogPagamento pagamento;
                pagamento = new FrmDialogPagamento(new javax.swing.JFrame(), true,  this.pedidosmodelo, null);
                pagamento.setVisible(true);
            }
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null,"erro: "+ e);
        }

//        FrmDialogPagamento pagamento = new FrmDialogPagamento(parent, true, vendamodelo);
    }//GEN-LAST:event_btnFinalizarActionPerformed

    private void btnGerenciarClientesActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGerenciarClientesActionPerformed
        // TODO add your handling code here:
        FrmDialogCliente frmcliente = new FrmDialogCliente(new javax.swing.JFrame(), true);
        frmcliente.setVisible(true);
    }//GEN-LAST:event_btnGerenciarClientesActionPerformed

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        listarClientes();
        txtTotal.setText(String.valueOf(total));
        Date dataSistema = new Date();
//        txtData.setDate(dataSistema);
    }//GEN-LAST:event_formWindowOpened

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here: 
        listarClientes();
    }//GEN-LAST:event_formWindowGainedFocus

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FinalizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FinalizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FinalizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FinalizarPedido.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FinalizarPedido dialog = new FinalizarPedido(new javax.swing.JFrame(), true, listaitenspedidosmodelo, funcionariomodelo, total);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnFinalizar;
    private javax.swing.JButton btnGerenciarClientes;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox cmbClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel lblImagemFundo;
    private javax.swing.JTextField txtDesconto;
    private javax.swing.JTextField txtHoraRetirada;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
