/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gestaodeestoque.Views;

import br.com.gestaodeestoque.Models.FuncionarioModelo;
import br.com.gestaodeestoque.dao.FuncionarioDAO;
import java.util.List;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Técnico
 */
public class FrmCadastroFuncionario extends javax.swing.JFrame {

    /**
     * Creates new form FrmCadastroFuncionario
     */
    public FrmCadastroFuncionario() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        btnLimpar = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        btnProcurar = new javax.swing.JButton();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        txtCadNome = new javax.swing.JTextField();
        txtCadEmail = new javax.swing.JTextField();
        txtCadLogin = new javax.swing.JTextField();
        txtCadCel = new javax.swing.JFormattedTextField();
        txtCadSenha = new javax.swing.JPasswordField();
        txtCadSenha1 = new javax.swing.JPasswordField();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        txtCadCod = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabelaCadUsu = new javax.swing.JTable();
        jLabel14 = new javax.swing.JLabel();
        chkExibirT = new javax.swing.JCheckBox();
        txtProcura = new javax.swing.JTextField();
        cmbPropriedades = new javax.swing.JComboBox<>();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jToolBar1.setFloatable(false);

        btnLimpar.setText("Novo");
        btnLimpar.setFocusable(false);
        btnLimpar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLimparActionPerformed(evt);
            }
        });
        jToolBar1.add(btnLimpar);

        btnInserir.setText("Salvar");
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInserir);

        btnAlterar1.setText("Alterar");
        btnAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterar1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAlterar1);

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluir);

        jLabel15.setFont(new java.awt.Font("Tahoma", 0, 30)); // NOI18N
        jLabel15.setText("|");
        jLabel15.setEnabled(false);
        jLabel15.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBar1.add(jLabel15);

        btnProcurar.setText("Procurar");
        btnProcurar.setFocusable(false);
        btnProcurar.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        btnProcurar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProcurarActionPerformed(evt);
            }
        });
        jToolBar1.add(btnProcurar);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel1.setText("Nome");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel2.setText("Email");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel3.setText("Celular");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 80, -1, -1));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel4.setText("Login");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 160, -1, -1));

        jLabel5.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel5.setText("Senha");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 160, -1, -1));

        txtCadNome.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadNomeActionPerformed(evt);
            }
        });
        jPanel1.add(txtCadNome, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 80, 500, -1));
        jPanel1.add(txtCadEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 120, 770, -1));
        jPanel1.add(txtCadLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 160, 240, -1));

        try {
            txtCadCel.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##)#####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        jPanel1.add(txtCadCel, new org.netbeans.lib.awtextra.AbsoluteConstraints(650, 80, 210, -1));
        jPanel1.add(txtCadSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(390, 160, 200, -1));
        jPanel1.add(txtCadSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(720, 160, 140, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel6.setText("Repita sua Senha");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 160, -1, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel7.setText("Código");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 40, -1, -1));

        txtCadCod.setEnabled(false);
        txtCadCod.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtCadCodActionPerformed(evt);
            }
        });
        jPanel1.add(txtCadCod, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 40, 180, -1));

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabelaCadUsu.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "id", "Nome", "Email", "Login", "Celular"
            }
        ));
        tabelaCadUsu.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tabelaCadUsuMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tabelaCadUsu);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 70, 1008, 220));

        jLabel14.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        jLabel14.setText("Procurar por");
        jPanel2.add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 10, -1, 20));

        chkExibirT.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        chkExibirT.setSelected(true);
        chkExibirT.setText("Exibir Todos");
        chkExibirT.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkExibirTItemStateChanged(evt);
            }
        });
        jPanel2.add(chkExibirT, new org.netbeans.lib.awtextra.AbsoluteConstraints(16, 30, -1, -1));
        jPanel2.add(txtProcura, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 40, 252, -1));

        cmbPropriedades.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Nome", "id", "email", "login", "celular" }));
        jPanel2.add(cmbPropriedades, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 10, 75, -1));

        jTabbedPane1.addTab("Funcionários Cadastrados", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1040, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 1040, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGap(0, 0, Short.MAX_VALUE)))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 380, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addGap(0, 0, Short.MAX_VALUE)
                    .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, 0)
                    .addComponent(jTabbedPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 330, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGap(0, 0, Short.MAX_VALUE)))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnLimparActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLimparActionPerformed
        // limpar
//        LimparDados();
    }//GEN-LAST:event_btnLimparActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        //cadastrar só O ESTOQUE E PEGAR O PROD OCM O NOME MAS NOS COD PELO ID
        String senha1, senha2;
        senha1 = txtCadSenha.getText();
        senha2 = txtCadSenha1.getText();

        //fazer um while para verificar
        if (txtCadNome.getText().equals("") || txtCadEmail.getText().equals("") || txtCadCel.getText().equals("")
            || txtCadLogin.getText().equals("") || txtCadSenha.equals("") || /*verificaçao da senha nao funciona*/ txtCadSenha.equals(null)) {
            if (txtCadNome.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Nome Invalido.");
            } else if (txtCadEmail.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Email Invalido.");
            } else if (txtCadCel.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Celular Invalido.");
            } else if (txtCadLogin.getText().equals("")) {
                JOptionPane.showMessageDialog(null, "Login Invalido.");
            } else if (txtCadSenha.equals("")) {
                JOptionPane.showMessageDialog(null, "Senha Invalido.");
            } else {
                JOptionPane.showMessageDialog(null, "Dados Invalidos.");
            }
        } else if (senha1.equals(senha2)) {
            try {
                FuncionarioModelo funcionariomodelo = new FuncionarioModelo();
                funcionariomodelo.setFuncionario_nome(txtCadNome.getText());
                funcionariomodelo.setFuncionario_email(txtCadEmail.getText());
                funcionariomodelo.setFuncionario_celular(txtCadCel.getText());
                funcionariomodelo.setFuncionario_login(txtCadLogin.getText());
                funcionariomodelo.setFuncionario_senha(txtCadSenha.getText());

                //metodo
                FuncionarioDAO dao = new FuncionarioDAO();
                dao.cadastraFuncionario(funcionariomodelo);

                JOptionPane.showMessageDialog(null, "Usuario cadastrado ");
//                ListarUsuario();

            } catch (Exception e) {

                JOptionPane.showMessageDialog(null, "Ops, ocorreu um erro: " + e);
            }
        }
    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterar1ActionPerformed
        // alterar
        try {
            //abrir form para escolher qual usuario deseja alterar
            FuncionarioModelo funcionariomodelo = new FuncionarioModelo();
            funcionariomodelo.setFuncionario_nome(txtCadNome.getText());
            funcionariomodelo.setFuncionario_email(txtCadEmail.getText());
            funcionariomodelo.setFuncionario_celular(txtCadCel.getText());
            funcionariomodelo.setFuncionario_login(txtCadLogin.getText());
            funcionariomodelo.setFuncionario_senha(txtCadSenha.getText());
            funcionariomodelo.setFuncionario_id(Integer.parseInt(txtCadCod.getText()));

            //metodo
            FuncionarioDAO dao = new FuncionarioDAO();
            dao.alterarUsuario(funcionariomodelo);

            JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
//            ListarUsuario();

        } catch (Exception e) {

            JOptionPane.showMessageDialog(null, "Ops, ocorreu um erro ao alterar os dados do usuário: " + e);
        }
    }//GEN-LAST:event_btnAlterar1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // exclui
        try {
            FuncionarioModelo funcionariomodelo = new FuncionarioModelo();

            funcionariomodelo.setFuncionario_id(Integer.parseInt(txtCadCod.getText()));

            FuncionarioDAO dao = new FuncionarioDAO();
            dao.excluirUsuario(funcionariomodelo);

            JOptionPane.showMessageDialog(null, "Dados excluidos com sucesso!");
//            ListarUsuario();
//            LimparDados();
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ops, ocorreu um erro ao excluir os dados: " + e);
        }
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnProcurarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProcurarActionPerformed
        if (txtProcura.getText().equals("")) {
            JOptionPane.showMessageDialog(null, "Campo vázio!");
        } else {
            try {
                chkExibirT.setSelected(false);
                FuncionarioDAO dao = new FuncionarioDAO();
                //                String tipodeSelect = cmbPropriedades.getSelectedItem().toString();
                String a = null;
                switch(cmbPropriedades.getSelectedItem().toString())
                {

                    case "id":
                    a="funcionario_id";
                    break;
                    case "Nome":
                    a="funcionario_nome";
                    break;
                    case "cel":
                    a="funcionario_celular";
                    break;
                    case "email":
                    a="funcionario_email";
                    break;

                }
                List<FuncionarioModelo> listadefuncionarios = dao.procurarFuncionariosPor("%" + txtProcura.getText() + "%", txtProcura);
                //                if (listadefuncionarios.equals(null)) {
                    //
                    //                    JOptionPane.showMessageDialog(null, "Funcionário não encontrado!");
                    //                } else {
                    DefaultTableModel modelo = (DefaultTableModel) tabelaCadUsu.getModel();
                    modelo.setNumRows(0);

                    for (FuncionarioModelo usumodel : listadefuncionarios) {
                        modelo.addRow(new Object[]{
                            usumodel.getFuncionario_id(),
                            usumodel.getFuncionario_nome(),
                            usumodel.getFuncionario_email(),
                            usumodel.getFuncionario_login(),
                            usumodel.getFuncionario_celular()
                        });
                    }
                    //                }
                JOptionPane.showMessageDialog(null, "ué");
            } catch (Exception e) {
                JOptionPane.showMessageDialog(null, "Nenhum registro encontrado." + e);
            }
        }
    }//GEN-LAST:event_btnProcurarActionPerformed

    private void txtCadNomeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadNomeActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadNomeActionPerformed

    private void txtCadCodActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtCadCodActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtCadCodActionPerformed

    private void tabelaCadUsuMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tabelaCadUsuMouseClicked
        //Pegar dados da Tabela
        txtCadCod.setText(tabelaCadUsu.getValueAt(tabelaCadUsu.getSelectedRow(), 0).toString());
        txtCadNome.setText(tabelaCadUsu.getValueAt(tabelaCadUsu.getSelectedRow(), 1).toString());
        txtCadEmail.setText(tabelaCadUsu.getValueAt(tabelaCadUsu.getSelectedRow(), 2).toString());
        txtCadCel.setText(tabelaCadUsu.getValueAt(tabelaCadUsu.getSelectedRow(), 4).toString());
        txtCadLogin.setText(tabelaCadUsu.getValueAt(tabelaCadUsu.getSelectedRow(), 3).toString());
        txtCadSenha.setText(null);
        txtCadSenha1.setText(null);
    }//GEN-LAST:event_tabelaCadUsuMouseClicked

    private void chkExibirTItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkExibirTItemStateChanged
        // TODO add your handling code here:
        if (chkExibirT.isSelected() == false) {
            DefaultTableModel modelo = (DefaultTableModel) tabelaCadUsu.getModel();
            modelo.setNumRows(0);
        } else {
//            ListarUsuario();
            txtProcura.setText("");
        }
    }//GEN-LAST:event_chkExibirTItemStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmCadastroFuncionario.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmCadastroFuncionario().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar1;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnLimpar;
    private javax.swing.JButton btnProcurar;
    private javax.swing.JCheckBox chkExibirT;
    private javax.swing.JComboBox<String> cmbPropriedades;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tabelaCadUsu;
    private javax.swing.JFormattedTextField txtCadCel;
    private javax.swing.JTextField txtCadCod;
    private javax.swing.JTextField txtCadEmail;
    private javax.swing.JTextField txtCadLogin;
    private javax.swing.JTextField txtCadNome;
    private javax.swing.JPasswordField txtCadSenha;
    private javax.swing.JPasswordField txtCadSenha1;
    private javax.swing.JTextField txtProcura;
    // End of variables declaration//GEN-END:variables
}
