/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gestaodeestoque.Views;

import br.com.gestaodeestoque.dao.FuncionarioDAO;
import javax.swing.JOptionPane;

/**
 *
 * @author Guibs
 */
public class FrmDialogRecuperacao extends javax.swing.JDialog {

    /**
     * Creates new form FrmDialogRecuperacao
     */
    public FrmDialogRecuperacao(java.awt.Frame parent, boolean modal) {
        super(parent, modal);
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        TablePane = new javax.swing.JTabbedPane();
        painelLogin = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtEmail1 = new javax.swing.JTextField();
        txtSenha1 = new javax.swing.JPasswordField();
        txtLogin1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        chkModificar1 = new javax.swing.JCheckBox();
        btnModificar1 = new javax.swing.JButton();
        painelSenha = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        txtLogin2 = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Recuperação");

        painelLogin.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informe os Dados Necessários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        painelLogin.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        painelLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel2.setText("Email");
        painelLogin.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, -1, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel3.setText("Senha");
        painelLogin.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 100, -1, -1));
        painelLogin.add(txtEmail1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 60, 390, -1));
        painelLogin.add(txtSenha1, new org.netbeans.lib.awtextra.AbsoluteConstraints(140, 100, 390, -1));

        txtLogin1.setEnabled(false);
        painelLogin.add(txtLogin1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 190, 290, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel1.setText("Seu Login é ");
        painelLogin.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 190, -1, -1));

        jButton1.setText("Recuperar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        painelLogin.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 150, -1, 20));

        chkModificar1.setText("Modificar Login");
        chkModificar1.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                chkModificar1ItemStateChanged(evt);
            }
        });
        painelLogin.add(chkModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 220, -1, -1));

        btnModificar1.setText("Modificar");
        btnModificar1.setEnabled(false);
        btnModificar1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnModificar1MouseClicked(evt);
            }
        });
        painelLogin.add(btnModificar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 250, -1, -1));

        TablePane.addTab("Recuperação de Login", painelLogin);

        painelSenha.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Informe os Dados Necessários", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 0, 14))); // NOI18N
        painelSenha.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        painelSenha.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 16)); // NOI18N
        jLabel4.setText("Login");
        painelSenha.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 90, -1, -1));

        jButton2.setText("Recuperar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        painelSenha.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 120, -1, -1));
        painelSenha.add(txtLogin2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 390, -1));

        TablePane.addTab("Recuperação de Senha", painelSenha);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 630, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(TablePane, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        setSize(new java.awt.Dimension(646, 399));
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        FuncionarioDAO dao = new FuncionarioDAO();
        txtLogin1.setText(dao.recuperarLogin(txtEmail1.getText().toString(), txtSenha1.getText().toString()));
    }//GEN-LAST:event_jButton1ActionPerformed

    private void chkModificar1ItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_chkModificar1ItemStateChanged
        // TODO add your handling code here:
        if(chkModificar1.isSelected() == true){
            txtLogin1.setEnabled(true);
            btnModificar1.setEnabled(true);
        } else {
            txtLogin1.setEnabled(false);
            btnModificar1.setEnabled(false);
        }
    }//GEN-LAST:event_chkModificar1ItemStateChanged

    private void btnModificar1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnModificar1MouseClicked
        // TODO add your handling code here:
        try {
            FuncionarioDAO dao = new FuncionarioDAO();
            dao.modificarLogin(txtEmail1.getText(), txtLogin1.getText());
            if (JOptionPane.showConfirmDialog(null, "Login alterado com sucesso!" + "\n" + "\n" +"Fechar e voltar para tela de login", "Alteração de Login", 0) == JOptionPane.YES_OPTION) {
                this.dispose();
            }
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "Ocorreu um erro ao alterar o login.");
        }
    }//GEN-LAST:event_btnModificar1MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        mailapp.MailApp.recuperação("funcionario_login", txtLogin2);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmDialogRecuperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmDialogRecuperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmDialogRecuperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmDialogRecuperacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                FrmDialogRecuperacao dialog = new FrmDialogRecuperacao(new javax.swing.JFrame(), true);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {
                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTabbedPane TablePane;
    private javax.swing.JButton btnModificar1;
    private javax.swing.JCheckBox chkModificar1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel painelLogin;
    private javax.swing.JPanel painelSenha;
    private javax.swing.JTextField txtEmail1;
    private javax.swing.JTextField txtLogin1;
    private javax.swing.JTextField txtLogin2;
    private javax.swing.JPasswordField txtSenha1;
    // End of variables declaration//GEN-END:variables
}
