/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gestaodeestoque.Views;

import br.com.gestaodeestoque.Utilities.Utilidades;
import br.com.gestaodeestoque.dao.FuncionarioDAO;
import java.awt.Graphics;
import java.awt.Image;
import java.awt.Toolkit;
import static java.lang.Thread.sleep;
import java.net.URL;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 *
 * @author Guibs
 */
public class FrmLogin extends javax.swing.JFrame {

    /**
     * Creates new form FrmLogin
     */
    public FrmLogin() {
        initComponents();
        btnEnviar.setVisible(false);
        ProgressBar.setVisible(false);
        lblIni.setVisible(false);
        lblIni1.setVisible(false);

                URL url = this.getClass().getResource("/imagesteste/logo controle de estoque.png");  
        Image iconeTitulo = Toolkit.getDefaultToolkit().getImage(url);
        this.setIconImage(iconeTitulo);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        painelInform = new javax.swing.JPanel();
        lblIni = new javax.swing.JLabel();
        lblIni1 = new javax.swing.JLabel();
        ProgressBar = new javax.swing.JProgressBar();
        jPanel2 = new javax.swing.JPanel();
        txtSenha = new javax.swing.JPasswordField();
        jLabel3 = new javax.swing.JLabel();
        txtLogin = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        btnEntrar = new javax.swing.JButton();
        btnSair = new javax.swing.JButton();
        lblNomeSoftware = new javax.swing.JLabel();
        cmbOpcoes = new javax.swing.JComboBox<>();
        btnEnviar = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Login");
        setResizable(false);
        addWindowFocusListener(new java.awt.event.WindowFocusListener() {
            public void windowGainedFocus(java.awt.event.WindowEvent evt) {
                formWindowGainedFocus(evt);
            }
            public void windowLostFocus(java.awt.event.WindowEvent evt) {
            }
        });
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        painelInform.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblIni.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIni.setText("Iniciando as Telas...");
        painelInform.add(lblIni, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 70, -1, -1));

        lblIni1.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        lblIni1.setText("Preparando os últimos detalhes...");
        painelInform.add(lblIni1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 70, 220, -1));
        painelInform.add(ProgressBar, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 90, 220, 20));

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel2.add(txtSenha, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, 320, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel3.setText("Senha");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 100, -1, -1));
        jPanel2.add(txtLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(49, 65, 320, -1));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 15)); // NOI18N
        jLabel2.setText("Login");
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 40, -1, -1));

        jCheckBox1.setText("Lembrar Usuário");
        jPanel2.add(jCheckBox1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));

        btnEntrar.setText("Entrar");
        btnEntrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEntrarActionPerformed(evt);
            }
        });
        jPanel2.add(btnEntrar, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 150, -1, -1));

        btnSair.setText("Sair");
        btnSair.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSairActionPerformed(evt);
            }
        });
        jPanel2.add(btnSair, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 150, 61, -1));

        painelInform.add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 410, 210));

        getContentPane().add(painelInform, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 190, 410, 210));

        lblNomeSoftware.setFont(new java.awt.Font("Segoe UI", 0, 36)); // NOI18N
        lblNomeSoftware.setText("GMG System");
        getContentPane().add(lblNomeSoftware, new org.netbeans.lib.awtextra.AbsoluteConstraints(460, 130, -1, -1));

        cmbOpcoes.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Opções", "Recuperação" }));
        cmbOpcoes.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbOpcoesItemStateChanged(evt);
            }
        });
        cmbOpcoes.addPropertyChangeListener(new java.beans.PropertyChangeListener() {
            public void propertyChange(java.beans.PropertyChangeEvent evt) {
                cmbOpcoesPropertyChange(evt);
            }
        });
        getContentPane().add(cmbOpcoes, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 11, 110, -1));

        btnEnviar.setText("Abrir");
        btnEnviar.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btnEnviarMouseClicked(evt);
            }
        });
        btnEnviar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEnviarActionPerformed(evt);
            }
        });
        getContentPane().add(btnEnviar, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 75, -1));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1118, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 30, Short.MAX_VALUE)
        );

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 580, -1, 30));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesteste/fundo do sftware.png"))); // NOI18N
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1120, 580));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
        if (txtLogin.getText().equals("") || txtLogin.getText().equals(null) || txtSenha.getText().equals("") || txtSenha.getText().equals(null)) {
            JOptionPane.showMessageDialog(null, "Campos vazios! Por favor, insira dados antes de logar");
        } else {

            FuncionarioDAO dao = new FuncionarioDAO();
            if (dao.efetuarLogin(txtLogin.getText(), txtSenha.getText()) == true) {
                
                ProgressBar.setVisible(true);
                lblIni.setVisible(true);
                new Thread(){
                    @Override
                    public void run(){
                        for(int i = 0; i < 101; i++){
                        try {
                            sleep(/*8*/ 1);
                            ProgressBar.setValue(i);
                                if(ProgressBar.getValue()>=50){
                                    lblIni.setVisible(false);
                            lblIni1.setVisible(true);
                            }
                           jPanel2.setVisible(false);
                        } catch (Exception erro) {
                            JOptionPane.showMessageDialog(null, erro);
                        }
                        }
                        
                    new FrmTelaInicial(dao.funcionarioAtual(txtLogin.getText())).setVisible(true);
                    FrmLogin.this.setVisible(false);
                    }  
                }.start();
//                if(jCheckBox1.getAutoscrolls()== true)
//                {
//                FuncionarioDAO dao1 = new FuncionarioDAO();
//                dao1.lembrarLogin(txtLogin.getText());
//                }
            } else {     
            JOptionPane.showMessageDialog(null, "Senha ou Login incorretos!");

            }  
        }
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void cmbOpcoesPropertyChange(java.beans.PropertyChangeEvent evt) {//GEN-FIRST:event_cmbOpcoesPropertyChange
        // TODO add your handling code here:
        
    }//GEN-LAST:event_cmbOpcoesPropertyChange

    private void cmbOpcoesItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbOpcoesItemStateChanged
        // TODO add your handling code here:
        if(cmbOpcoes.getSelectedIndex() == 0 ){
        btnEnviar.setVisible(false);
        }else {
        btnEnviar.setVisible(true);
        }
    }//GEN-LAST:event_cmbOpcoesItemStateChanged

    private void btnEnviarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEnviarActionPerformed
        // TODO add your handling code here:

    }//GEN-LAST:event_btnEnviarActionPerformed

    private void btnSairActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSairActionPerformed
        Utilidades.sairSimNao();
    }//GEN-LAST:event_btnSairActionPerformed

    private void btnEnviarMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btnEnviarMouseClicked
        // TODO add your handling code here:
        
                    if (cmbOpcoes.getSelectedIndex() == 1) {
                FrmDialogRecuperacao esqueceuSenha = new FrmDialogRecuperacao(this, rootPaneCheckingEnabled);

                esqueceuSenha.setVisible(true);
            }

    }//GEN-LAST:event_btnEnviarMouseClicked

    private void formWindowGainedFocus(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowGainedFocus
        // TODO add your handling code here:
        txtLogin.grabFocus();
    }//GEN-LAST:event_formWindowGainedFocus

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        // TODO add your handling code here:
        txtLogin.setText("guibs");
        txtSenha.setText("guibs");
    }//GEN-LAST:event_formWindowOpened

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(FrmLogin.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new FrmLogin().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar ProgressBar;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JButton btnEnviar;
    private javax.swing.JButton btnSair;
    private javax.swing.JComboBox<String> cmbOpcoes;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel lblIni;
    private javax.swing.JLabel lblIni1;
    private javax.swing.JLabel lblNomeSoftware;
    private javax.swing.JPanel painelInform;
    private javax.swing.JTextField txtLogin;
    private javax.swing.JPasswordField txtSenha;
    // End of variables declaration//GEN-END:variables
}
