/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package br.com.gestaodeestoque.Views;

import br.com.gestaodeestoque.Models.EventosModelo;
import br.com.gestaodeestoque.dao.EstoqueDAO;
import br.com.gestaodeestoque.dao.EventosDAO;
import java.text.SimpleDateFormat;
import javax.swing.JOptionPane;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Guibs
 */
public class InternalFrmEventos extends javax.swing.JInternalFrame {

    /**
     * Creates new form InternalFrmNovosEventos
     */
    public InternalFrmEventos() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txtDescricao = new javax.swing.JTextField();
        txtTitulo = new javax.swing.JTextField();
        txtTermino = new com.toedter.calendar.JDateChooser();
        txtInicio = new com.toedter.calendar.JDateChooser();
        imagemfundo = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tabela_eventos = new javax.swing.JTable();
        jToolBar1 = new javax.swing.JToolBar();
        btnNovo = new javax.swing.JButton();
        btnInserir = new javax.swing.JButton();
        btnAlterar1 = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();

        setClosable(true);
        setTitle("Cadastro de Eventos");
        addInternalFrameListener(new javax.swing.event.InternalFrameListener() {
            public void internalFrameActivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosed(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameClosing(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeactivated(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameDeiconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameIconified(javax.swing.event.InternalFrameEvent evt) {
            }
            public void internalFrameOpened(javax.swing.event.InternalFrameEvent evt) {
                formInternalFrameOpened(evt);
            }
        });
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel6.setText("Descrição");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 90, -1, -1));

        jLabel8.setText("Evento Título");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 60, -1, -1));

        jLabel9.setText("Data início");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 120, -1, -1));

        jLabel10.setText("Data Termino");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(290, 120, -1, -1));
        jPanel1.add(txtDescricao, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 90, 370, -1));
        jPanel1.add(txtTitulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 60, 370, -1));
        jPanel1.add(txtTermino, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 120, 140, -1));
        jPanel1.add(txtInicio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 120, 140, -1));

        imagemfundo.setFont(new java.awt.Font("Tahoma", 0, 13)); // NOI18N
        imagemfundo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/imagesteste/fundo_opaco.png"))); // NOI18N
        jPanel1.add(imagemfundo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 870, 240));

        jTabbedPane1.addTab("Cadastro", jPanel1);

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabela_eventos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Título", "Data de Inicio", "Descrição", "Data de Termino"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabela_eventos);

        jPanel2.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 600, 190));

        jTabbedPane1.addTab("Todos os Eventos", jPanel2);

        getContentPane().add(jTabbedPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 50, 630, 270));

        jToolBar1.setBorder(javax.swing.BorderFactory.createEtchedBorder(javax.swing.border.EtchedBorder.RAISED));
        jToolBar1.setFloatable(false);

        btnNovo.setText("Novo");
        btnNovo.setFocusable(false);
        btnNovo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoActionPerformed(evt);
            }
        });
        jToolBar1.add(btnNovo);

        btnInserir.setText("Salvar");
        btnInserir.setFocusable(false);
        btnInserir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnInserirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnInserir);

        btnAlterar1.setText("Alterar");
        btnAlterar1.setFocusable(false);
        btnAlterar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlterar1ActionPerformed(evt);
            }
        });
        jToolBar1.add(btnAlterar1);

        btnExcluir.setText("Excluir");
        btnExcluir.setFocusable(false);
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });
        jToolBar1.add(btnExcluir);

        jButton3.setText("Procurar");
        jButton3.setFocusable(false);
        jButton3.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jToolBar1.add(jButton3);

        getContentPane().add(jToolBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 630, 50));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void ListarEventos() {
        try {
            EventosDAO novodao = new EventosDAO();
            List<EventosModelo> listadeeventos = novodao.listarEventos();
//            this.listadeestoque = listadeestoque;
            DefaultTableModel modelo = (DefaultTableModel) tabela_eventos.getModel();
            modelo.setNumRows(0);
            
            for (EventosModelo eventosmodelo : listadeeventos) {
//                CategoriaModelo categoria = new CategoriaModelo();
//                SubCategoriaModelo subcategoria = new SubCategoriaModelo();
                modelo.addRow(new Object[]{
                    eventosmodelo.getData_inicio(),
                    eventosmodelo.getEvento_data_termino(),
                    eventosmodelo.getEvento_desc(),
                    eventosmodelo.getEvento_titulo()
                });
            }
        } catch (Exception e) {
            throw new RuntimeException("Ops, ocorreu um erro ao listar os Produtos" + e);
        }
    }

    public void LimparDados() {
        txtDescricao.setText("");
        txtInicio.setDate(null);
        txtTermino.setDate(null);
        txtTitulo.setText("");
    }
    private void btnNovoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoActionPerformed
        // limpar
        LimparDados();
    }//GEN-LAST:event_btnNovoActionPerformed

    private void btnInserirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnInserirActionPerformed
        try {
            EventosModelo eventomodelo = new EventosModelo();
            eventomodelo.setEvento_titulo(txtTitulo.getText());
            eventomodelo.setEvento_desc(txtDescricao.getText());

            SimpleDateFormat formatador = new SimpleDateFormat("yyyy-MM-dd");
            String dataformatada = formatador.format(txtInicio.getDate());
            eventomodelo.setData_inicio(dataformatada);

            String dataformatada2 = formatador.format(txtTermino.getDate());
            eventomodelo.setEvento_data_termino(dataformatada2);
            EventosDAO eventosdao = new EventosDAO();
            eventosdao.inserirEventos(eventomodelo);
            JOptionPane.showMessageDialog(null, "Evento Cadastrado com sucesso!");
        } catch (Exception e) {
            JOptionPane.showMessageDialog(null, "erro ao cadastrar evento: " + e);
        }


    }//GEN-LAST:event_btnInserirActionPerformed

    private void btnAlterar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterar1ActionPerformed
        /* alterar
        if (txtCadProdId.getText().equals("") || txtCadProdId.getText().equals(null)) {

            JOptionPane.showMessageDialog(null, "Campo ID produto vazio, tente selecionar a tabela novamente.");
        } else {
            if (JOptionPane.showConfirmDialog(null, "Deseja realmente alterar campo?","Alteração de Campos",2)== JOptionPane.OK_OPTION) {
                try {
                    ProdutoModelo produtomodelo = new ProdutoModelo();
                    produtomodelo.setNomeProduto(txtCadNome.getText());
                    produtomodelo.setDescProduto(txtCadDesc.getText());

                    produtomodelo.setValidadeProduto(dataParaMysql(txtCadVal.getText()));

                    produtomodelo.setIdProduto(Integer.parseInt(txtCadProdId.getText()));

                    //metodo
                    ProdutoDAO dao = new ProdutoDAO();
                    dao.alterarProduto(produtomodelo);

                    JOptionPane.showMessageDialog(null, "Dados alterados com sucesso!");
                    ListarProdutos();
                    LimparDados();
                } catch (Exception e) {

                    JOptionPane.showMessageDialog(null, "Ops, ocorreu um erro ao alterar os dados do produto: " + e);
                }
            }
        }*/
    }//GEN-LAST:event_btnAlterar1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed

    }//GEN-LAST:event_btnExcluirActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        //        String nomedaProcura = txtNomeProcura.getText();
        //        try {
        //            ProdutoModelo modelo = new ProdutoModelo();
        //            modelo.setNomeProduto(nomedaProcura);
        //            ProdutoDAO dao = new ProdutoDAO();
        //            String produtoprocurado = dao.ProcurarProduto(modelo).toString();
        //
        //        } catch (Exception e) {
        //            JOptionPane.showMessageDialog(null, "Erro ao Procurar Produto: " + e);
        //        }
    }//GEN-LAST:event_jButton3ActionPerformed

    private void formInternalFrameOpened(javax.swing.event.InternalFrameEvent evt) {//GEN-FIRST:event_formInternalFrameOpened
    ListarEventos();        // TODO add your handling code here:
    }//GEN-LAST:event_formInternalFrameOpened


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterar1;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JButton btnInserir;
    private javax.swing.JButton btnNovo;
    private javax.swing.JLabel imagemfundo;
    private javax.swing.JButton jButton3;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTable tabela_eventos;
    private javax.swing.JTextField txtDescricao;
    private com.toedter.calendar.JDateChooser txtInicio;
    private com.toedter.calendar.JDateChooser txtTermino;
    private javax.swing.JTextField txtTitulo;
    // End of variables declaration//GEN-END:variables
}
